###

GET http://127.0.0.1:8000/api/models

###

GET http://127.0.0.1:8000/api/models/1

###

POST http://127.0.0.1:8000/api/jobs
Content-Type: application/json

{
  "modelId": 1,
  "videoUrl": "hello"
}