const fs = require('fs')

const hostile = [
  'skeleton', 'wither_skeleton', 'zombie', 'zombie_villager', 'creeper', 'spider', 'cave_spider',
  'piglin', 'piglin_brute', 'pillager', 'zombified_piglin', 'drowned', 'wither', 'ender_dragon',
  'enderman', 'endermite', 'ghast', 'slime', 'magma_cube', 'blaze', 'hoglin', 'zoglin', 'phantom',
  'silverfish', 'ravager', 'illusioner', 'vindicator', 'warden'
].map((ent, idx) => [ent, idx + 1]) 
const friendly = [
  'armadillo', 'axolotl', 'bat', 'bee', 'camel', 'donkey', 'llama', 'horse', 'mule', 'trader_llama',
  'goat', 'cat', 'ocelot', 'chicken', 'cod', 'frog', 'tropical_fish', 'turtle', 'tadpole', 'salmon',
  'pufferfish', 'cow', 'mooshroom', 'dolphin', 'fox', 'iron_golem', 'snow_golem', 'panda', 'parrot',
  'pig', 'polar_bear', 'rabbit', 'sheep', 'skeleton_horse', 'squid', 'glow_squid', 'strider',
  'villager', 'wandering_trader', 'wolf'
].map((ent, idx) => [ent, idx + 128])
const neutral = [
  'player', 'item'
].map((ent, idx) => [ent, idx + 256])
const unlit = [
  'minecraft:entity_flame'
].map((ent) => [ent, 511])

fs.writeFileSync(__dirname + '/shaders/entity.properties', [
  '# Generated by generate_entityprop.js, because I am a lazy ass.',
  '# In full honesty, it\'s just the numbering of IDs',
  '',
  '# Hostile Mobs',
  ...hostile.map(([ent, idx]) => `entity.${idx} = ${ent}`),
  '',
  '# Friendly Mobs',
  ...friendly.map(([ent, idx]) => `entity.${idx} = ${ent}`),
  '',
  '# Neutral/Noteworthy entities',
  ...neutral.map(([ent, idx]) => `entity.${idx} = ${ent}`),
  '',
  '# Unlit',
  ...unlit.map(([ent, idx]) => `entity.${idx} = ${ent}`),
  '',
  '# In case we need "merged buffers" again',
  `# entity.999 = ${hostile.join(' ')}`,
  `# entity.999 = ${friendly.join(' ')}`,
  `# entity.999 = ${neutral.join(' ')}`
].join('\n'))

fs.writeFileSync(__dirname + '/entities.json', JSON.stringify(
  [
    ...hostile,
    ...friendly,
    ...neutral,
    ...unlit
  ].reduce((acc, [name, idx]) => {
    acc[name] = idx
    return acc
  }, {})  
, null, 4))