name: deploy minimal web
on:
  push:
    branches: [ "minimal" ]
  pull_request:
    branches: [ "minimal" ]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: nodejs setup
        uses: actions/setup-node@v7
        with:
          node-version: lts/*
          cache: 'npm'
          cache-dependency-path: './web/package-lock.json'
      - name: build
        working-directory: ./web
        run: |
          npm ci
          npm run build
      - name: upload
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: './web/dist'
  deployment:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: deployment
        id: deployment
        uses: actions/deploy-pages@v4
